// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../billnogenerator/BillCounter.dart';
import 'menu_item.dart';
import 'transaction.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1019123645680910039),
      name: 'BillCounter',
      lastPropertyId: const obx_int.IdUid(2, 5914349024876171738),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8695992857360080676),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5914349024876171738),
            name: 'lastBillNo',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3582577871583635519),
      name: 'MenuItem',
      lastPropertyId: const obx_int.IdUid(23, 5733070948939132250),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5513895496785653328),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4314474408438079815),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3090093852456933090),
            name: 'sellPrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8609622646886032539),
            name: 'sellPriceType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1599641091626051587),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2861219584207510589),
            name: 'mrp',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5593189061636039987),
            name: 'purchasePrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8590849805474482848),
            name: 'acSellPrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7313573036249261136),
            name: 'nonAcSellPrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8432291160507611693),
            name: 'onlineDeliveryPrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 8589446624660179125),
            name: 'onlineSellPrice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 8531729988208766765),
            name: 'hsnCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 3610426219220378359),
            name: 'itemCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 8442569207793758908),
            name: 'barCode',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7363542963920796319),
            name: 'barCode2',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 3892497017337573094),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 394020576652223949),
            name: 'available',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 9019984288974176565),
            name: 'adjustStock',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 7099351567907957224),
            name: 'gstRate',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 4829485124407521824),
            name: 'withTax',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 2989306200332019824),
            name: 'cessRate',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 1302914077306052551),
            name: 'selected',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 5733070948939132250),
            name: 'qty',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 6864652018561019037),
      name: 'Transaction',
      lastPropertyId: const obx_int.IdUid(5, 2247625801660169757),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8786320978196448423),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7679587270166320258),
            name: 'time',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8091580902238673261),
            name: 'tableNo',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3473461810160574889),
            name: 'total',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2247625801660169757),
            name: 'cartData',
            type: 23,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 6864652018561019037),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    BillCounter: obx_int.EntityDefinition<BillCounter>(
        model: _entities[0],
        toOneRelations: (BillCounter object) => [],
        toManyRelations: (BillCounter object) => {},
        getId: (BillCounter object) => object.id,
        setId: (BillCounter object, int id) {
          object.id = id;
        },
        objectToFB: (BillCounter object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.lastBillNo);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final lastBillNoParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = BillCounter(lastBillNo: lastBillNoParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    MenuItem: obx_int.EntityDefinition<MenuItem>(
        model: _entities[1],
        toOneRelations: (MenuItem object) => [],
        toManyRelations: (MenuItem object) => {},
        getId: (MenuItem object) => object.id,
        setId: (MenuItem object, int id) {
          object.id = id;
        },
        objectToFB: (MenuItem object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final sellPriceOffset = fbb.writeString(object.sellPrice);
          final sellPriceTypeOffset = fbb.writeString(object.sellPriceType);
          final categoryOffset = fbb.writeString(object.category);
          final mrpOffset =
              object.mrp == null ? null : fbb.writeString(object.mrp!);
          final purchasePriceOffset = object.purchasePrice == null
              ? null
              : fbb.writeString(object.purchasePrice!);
          final acSellPriceOffset = object.acSellPrice == null
              ? null
              : fbb.writeString(object.acSellPrice!);
          final nonAcSellPriceOffset = object.nonAcSellPrice == null
              ? null
              : fbb.writeString(object.nonAcSellPrice!);
          final onlineDeliveryPriceOffset = object.onlineDeliveryPrice == null
              ? null
              : fbb.writeString(object.onlineDeliveryPrice!);
          final onlineSellPriceOffset = object.onlineSellPrice == null
              ? null
              : fbb.writeString(object.onlineSellPrice!);
          final hsnCodeOffset =
              object.hsnCode == null ? null : fbb.writeString(object.hsnCode!);
          final itemCodeOffset = object.itemCode == null
              ? null
              : fbb.writeString(object.itemCode!);
          final barCodeOffset =
              object.barCode == null ? null : fbb.writeString(object.barCode!);
          final barCode2Offset = object.barCode2 == null
              ? null
              : fbb.writeString(object.barCode2!);
          final imagePathOffset = object.imagePath == null
              ? null
              : fbb.writeString(object.imagePath!);
          fbb.startTable(24);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, sellPriceOffset);
          fbb.addOffset(3, sellPriceTypeOffset);
          fbb.addOffset(4, categoryOffset);
          fbb.addOffset(5, mrpOffset);
          fbb.addOffset(6, purchasePriceOffset);
          fbb.addOffset(7, acSellPriceOffset);
          fbb.addOffset(8, nonAcSellPriceOffset);
          fbb.addOffset(9, onlineDeliveryPriceOffset);
          fbb.addOffset(10, onlineSellPriceOffset);
          fbb.addOffset(11, hsnCodeOffset);
          fbb.addOffset(12, itemCodeOffset);
          fbb.addOffset(13, barCodeOffset);
          fbb.addOffset(14, barCode2Offset);
          fbb.addOffset(15, imagePathOffset);
          fbb.addInt64(16, object.available);
          fbb.addInt64(17, object.adjustStock);
          fbb.addFloat64(18, object.gstRate);
          fbb.addBool(19, object.withTax);
          fbb.addFloat64(20, object.cessRate);
          fbb.addBool(21, object.selected);
          fbb.addInt64(22, object.qty);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final sellPriceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final sellPriceTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final mrpParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final purchasePriceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final acSellPriceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final nonAcSellPriceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 20);
          final onlineDeliveryPriceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final onlineSellPriceParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final hsnCodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final itemCodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final barCodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final barCode2Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 32);
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 34);
          final availableParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 36);
          final adjustStockParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 38);
          final gstRateParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 40);
          final withTaxParam =
              const fb.BoolReader().vTableGetNullable(buffer, rootOffset, 42);
          final cessRateParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 44);
          final selectedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 46, false);
          final qtyParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 48, 0);
          final object = MenuItem(
              id: idParam,
              name: nameParam,
              sellPrice: sellPriceParam,
              sellPriceType: sellPriceTypeParam,
              category: categoryParam,
              mrp: mrpParam,
              purchasePrice: purchasePriceParam,
              acSellPrice: acSellPriceParam,
              nonAcSellPrice: nonAcSellPriceParam,
              onlineDeliveryPrice: onlineDeliveryPriceParam,
              onlineSellPrice: onlineSellPriceParam,
              hsnCode: hsnCodeParam,
              itemCode: itemCodeParam,
              barCode: barCodeParam,
              barCode2: barCode2Param,
              imagePath: imagePathParam,
              available: availableParam,
              adjustStock: adjustStockParam,
              gstRate: gstRateParam,
              withTax: withTaxParam,
              cessRate: cessRateParam,
              selected: selectedParam,
              qty: qtyParam);

          return object;
        }),
    Transaction: obx_int.EntityDefinition<Transaction>(
        model: _entities[2],
        toOneRelations: (Transaction object) => [],
        toManyRelations: (Transaction object) => {},
        getId: (Transaction object) => object.id,
        setId: (Transaction object, int id) {
          object.id = id;
        },
        objectToFB: (Transaction object, fb.Builder fbb) {
  final cartDataOffset = fbb.writeString(object.cartData);
  //final timeOffset = fbb.writeString(object.time);

  fbb.startTable(6);
  fbb.addInt64(0, object.id);
 // fbb.addOffset(1, timeOffset); // use string for time
  fbb.addInt64(2, object.tableNo);
  fbb.addInt64(3, object.total);
  fbb.addOffset(4, cartDataOffset);
  fbb.finish(fbb.endTable());
  return object.id;
}
,
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final timeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0));
          final tableNoParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 8);
          final totalParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final cartDataParam =
              const fb.StringReader()
                      .vTableGet(buffer, rootOffset, 12, '');
          final object = Transaction(
              //time: timeParam,
              tableNo: tableNoParam,
              total: totalParam,
              cartData: cartDataParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BillCounter] entity fields to define ObjectBox queries.
class BillCounter_ {
  /// See [BillCounter.id].
  static final id =
      obx.QueryIntegerProperty<BillCounter>(_entities[0].properties[0]);

  /// See [BillCounter.lastBillNo].
  static final lastBillNo =
      obx.QueryIntegerProperty<BillCounter>(_entities[0].properties[1]);
}

/// [MenuItem] entity fields to define ObjectBox queries.
class MenuItem_ {
  /// See [MenuItem.id].
  static final id =
      obx.QueryIntegerProperty<MenuItem>(_entities[1].properties[0]);

  /// See [MenuItem.name].
  static final name =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[1]);

  /// See [MenuItem.sellPrice].
  static final sellPrice =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[2]);

  /// See [MenuItem.sellPriceType].
  static final sellPriceType =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[3]);

  /// See [MenuItem.category].
  static final category =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[4]);

  /// See [MenuItem.mrp].
  static final mrp =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[5]);

  /// See [MenuItem.purchasePrice].
  static final purchasePrice =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[6]);

  /// See [MenuItem.acSellPrice].
  static final acSellPrice =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[7]);

  /// See [MenuItem.nonAcSellPrice].
  static final nonAcSellPrice =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[8]);

  /// See [MenuItem.onlineDeliveryPrice].
  static final onlineDeliveryPrice =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[9]);

  /// See [MenuItem.onlineSellPrice].
  static final onlineSellPrice =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[10]);

  /// See [MenuItem.hsnCode].
  static final hsnCode =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[11]);

  /// See [MenuItem.itemCode].
  static final itemCode =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[12]);

  /// See [MenuItem.barCode].
  static final barCode =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[13]);

  /// See [MenuItem.barCode2].
  static final barCode2 =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[14]);

  /// See [MenuItem.imagePath].
  static final imagePath =
      obx.QueryStringProperty<MenuItem>(_entities[1].properties[15]);

  /// See [MenuItem.available].
  static final available =
      obx.QueryIntegerProperty<MenuItem>(_entities[1].properties[16]);

  /// See [MenuItem.adjustStock].
  static final adjustStock =
      obx.QueryIntegerProperty<MenuItem>(_entities[1].properties[17]);

  /// See [MenuItem.gstRate].
  static final gstRate =
      obx.QueryDoubleProperty<MenuItem>(_entities[1].properties[18]);

  /// See [MenuItem.withTax].
  static final withTax =
      obx.QueryBooleanProperty<MenuItem>(_entities[1].properties[19]);

  /// See [MenuItem.cessRate].
  static final cessRate =
      obx.QueryDoubleProperty<MenuItem>(_entities[1].properties[20]);

  /// See [MenuItem.selected].
  static final selected =
      obx.QueryBooleanProperty<MenuItem>(_entities[1].properties[21]);

  /// See [MenuItem.qty].
  static final qty =
      obx.QueryIntegerProperty<MenuItem>(_entities[1].properties[22]);
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.id].
  static final id =
      obx.QueryIntegerProperty<Transaction>(_entities[2].properties[0]);

  /// See [Transaction.time].
  static final time =
      obx.QueryDateProperty<Transaction>(_entities[2].properties[1]);

  /// See [Transaction.tableNo].
  static final tableNo =
      obx.QueryIntegerProperty<Transaction>(_entities[2].properties[2]);

  /// See [Transaction.total].
  static final total =
      obx.QueryIntegerProperty<Transaction>(_entities[2].properties[3]);

  /// See [Transaction.cartData].
  static final cartData =
      obx.QueryByteVectorProperty<Transaction>(_entities[2].properties[4]);
}
